### ISSUE TITLE
Cadastro de Usuários

### ISSUE THREAD

**Issue by jgabrielmaia** [ufjf-dcc195/dcc195-2019-3-trb2#2]
Esta entidade não é a usuária do sistema, e sim o autor do contato.

Atributos:
- Identificador
- Nome
- CPF
- Telefone
- Identificador Unidade Principal 
- Identificador Unidade Secundária
- E-mail
- Já Realizou Curso

**Comment by JoaoPDias** [comment]
API concluída com os endpoints de CRUD
