### ISSUE TITLE
Quantidade de atendimentos por tipo de dúvida frequente

### ISSUE THREAD

**Issue by jgabrielmaia** [ufjf-dcc195/dcc195-2019-3-trb2#8]
Tipos de Dúvida frequente:
- Cadastro PCDP
- Legislação
- Relatórios
- Prestação de Contas
- Alteração PCDP

**Comment by douglasBaumgratz** [comment]
Estou trabalhando nessa issue

**Comment by douglasBaumgratz** [comment]
Finalizada

**Comment by douglasBaumgratz** [comment]
Finalizado backend

**Comment by douglasBaumgratz** [comment]
Finalizado frontend
